/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Account: typeof import('./components/Account.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    ConnectDialog: typeof import('./components/ConnectDialog.vue')['default']
    NftCard: typeof import('./components/NftCard.vue')['default']
    NftGallery: typeof import('./components/NftGallery.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TransferDialog: typeof import('./components/TransferDialog.vue')['default']
  }
}
